In [1]:
import numpy as np
a = np.matrix([[1,0], [2,-1]])
r = a * a

In [2]:
r

matrix([[1, 0],
        [0, 1]])

In [3]:
a = np.array ([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [4]:
a = np. array([ [1,2], [3,4] ])
print(np.mean(a, axis=None)== np.mean(a))

True


In [5]:
a = np.array([[1,0], [2, -1]])
r = a * a

In [6]:
r

array([[1, 0],
       [4, 1]])

In [7]:
a = np.array([1,2,3, []])
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [8]:
np.random.random((2,2))

array([[0.47822071, 0.50957177],
       [0.84030663, 0.74093986]])

In [9]:
a = np.array( [[1,2, 3, 4], [5,6, 7, 8], [9,10,11,12]])
b = a[1:3, 2:]

In [10]:
b

array([[ 7,  8],
       [11, 12]])

In [11]:
a = np. array([ [1,2], [3,4]])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [12]:
a = np.array([[1,1], [2,0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [13]:
x

array([[1., 0.],
       [0., 0.]])

In [14]:
y

matrix([[1., 1.],
        [2., 0.]])

In [16]:
a = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1,0]
a[0,0]= a[0,2] + a[2,0]

In [18]:
a

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  0]])

In [19]:
a = np.array([[1,2], [3,4]])
b = [a[j,i] for i in range (a.shape[0]) for j in range(a.shape[1])]

In [20]:
b

[1, 3, 2, 4]

In [24]:
a = np.array([[1,2,3], [4,5,6]])
b = a.reshape(-1)

In [22]:
b

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.zeros((2,2))
b = np.eye(2)

In [28]:
a

array([[0., 0.],
       [0., 0.]])

In [29]:
b

array([[1., 0.],
       [0., 1.]])

In [30]:
a = np.array([[1,2,3], [4,5,6]])
b = a.T

In [31]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
a = np.array([[10,11,12]])
b = np.array([[20],[21],[22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [33]:
a = np.array([[1,1], [2,0]])
b =np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [34]:
x

array([[1., 0.],
       [0., 0.]])

In [36]:
y

matrix([[1., 1.],
        [2., 0.]])

In [37]:
b = np.mat([[5,6],[7,8]])
b.type

AttributeError: 'matrix' object has no attribute 'type'

In [38]:
a = np.zeros((2,2))
b = np.eye(2)

In [39]:
a
b

array([[1., 0.],
       [0., 1.]])

In [40]:
a = np.ones(2)
b = np.ones((1,2))

In [41]:
a
b

array([[1., 1.]])

In [42]:
a = np.array ([[1,2,3,4,5], [6,7,8,9,10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]

In [43]:
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])