# Michael Reese
## Week 11 - 4/4/2021
### Python Numpy Universal Functions

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z=[]

for i, j in zip (arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [2]:
#zip

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([ 0.61655564, -1.04022169, -0.48687721, -0.99139178,  0.47851077,
       -1.00019533,  0.16184285, -0.44252186, -1.34136953,  1.01118294])

In [9]:
arr2 = np.random.randn(10)

arr2

array([ 0.72534898,  0.35322473,  1.47605833, -0.80234278,  1.29740957,
        0.22166943, -0.47813479, -1.5267258 ,  1.12413267,  1.05025379])

In [10]:
np.add(arr1,arr2)

array([ 1.34190462, -0.68699696,  0.98918112, -1.79373456,  1.77592034,
       -0.7785259 , -0.31629195, -1.96924766, -0.21723687,  2.06143673])

In [11]:
np.maximum(arr1,arr2)

array([ 0.72534898,  0.35322473,  1.47605833, -0.80234278,  1.29740957,
        0.22166943,  0.16184285, -0.44252186,  1.12413267,  1.05025379])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [15]:
np.where((arr<4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)
print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [18]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [21]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [23]:
np.where([[True,False],[True,True]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [26]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 0.34004983,  0.47407281,  0.59488847],
       [-0.65975519,  0.50567986, -1.95271455],
       [-0.67599826, -1.39982744,  0.49088145]])

In [27]:
np.where(arr<0, 0,arr)

array([[0.34004983, 0.47407281, 0.59488847],
       [0.        , 0.50567986, 0.        ],
       [0.        , 0.        , 0.49088145]])

In [28]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [29]:
arr_b.all()

False

In [30]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [31]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [34]:
#Statistical measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
arr.sum()

45

In [36]:
arr.sum(0)

array([12, 15, 18])

In [37]:
arr.sum(1)

array([ 6, 15, 24])

In [39]:
#intentional error
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [40]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [41]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [43]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [45]:
arr.mean()

5.0

In [46]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [47]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [49]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [51]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [52]:
arr.var()

6.666666666666667

In [54]:
arr.std()

2.581988897471611

In [55]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])
arr.sort()
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [56]:
#identity array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [59]:
i =np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))

a * i

array([[0., 0.],
       [0., 3.]])

In [60]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [61]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [64]:
# Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print('---------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
---------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [65]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [66]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
arr.transpose(1,0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [70]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [71]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [72]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [73]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [74]:
np.random.random((4,4))

array([[0.29981553, 0.45253594, 0.33358777, 0.72911391],
       [0.78991799, 0.41749632, 0.73021514, 0.63018375],
       [0.68941901, 0.84116581, 0.49045666, 0.18295646],
       [0.01981881, 0.64896358, 0.13641517, 0.51437695]])

In [76]:
from numpy.random import random
random((4,4))

array([[0.80383049, 0.29081986, 0.32366984, 0.53912032],
       [0.67474705, 0.42928238, 0.43457506, 0.26632354],
       [0.50541178, 0.47186377, 0.20860382, 0.07095788],
       [0.04115969, 0.27400234, 0.37795731, 0.00601514]])

In [77]:
from numpy.random import randn
randn(5,5)

array([[-0.27256798,  0.59743599,  0.79897132,  0.45929184, -0.10736514],
       [ 1.09257921, -1.3390455 ,  0.36163637,  0.28874165, -0.95143041],
       [-0.25380376,  0.86651783,  0.60454071, -0.16469825,  0.48687726],
       [-0.34186869,  1.31639372,  0.65160338,  1.21670457,  0.91067921],
       [-0.22126685, -0.62938085, -0.40130863, -0.74564065,  0.92804442]])

In [78]:
randn(5)

array([-1.18821782,  0.61567173,  0.27750816,  0.62349508, -2.90790438])

In [79]:
np.random.randint(10,50)

35

In [81]:
website = "docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [82]:
import pandas as pd